In [1]:
import numpy as np
LIST = [1,2,3,4,7]
arr = np.array([1,2,3,4,7])
type (arr)

numpy.ndarray

# 认识numpy

In [2]:
print (LIST[0])

1


In [3]:
print(arr[1])

2


In [4]:
arr[2:]

array([3, 4, 7])

In [5]:
print (arr[2:])

LIST[-1] = 'string'

print(LIST[2:])

[3 4 7]
[3, 4, 'string']


In [6]:
#arr[-1]='string'#报错：一旦numpy的数组创建完成，dtype就是固定的，不可以改变

In [7]:
arr.dtype #输出arr矩阵的dtype

dtype('int32')

In [8]:
arr[-1] = 14.23 #整数类型的数组中添加一个浮点类型数

In [9]:
arr#自动将浮点类型转为整数类型

array([ 1,  2,  3,  4, 14])

# 数组的创建

In [10]:
np.zeros(5,dtype = float)#创建一个浮点类型的值为0，长度为5的数组

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [12]:
np.ones(5,dtype =float)#创建一个浮点类型的值为1，长度为5的数组

array([ 1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [14]:
a = np.empty(4)#定义一个长度为4的空数组

In [15]:
a.fill(5.5)#将空数组用5.5填充
a

array([ 5.5,  5.5,  5.5,  5.5])

In [16]:
np.random.randn(5)#用np.random创建一个长度为5的随机数组,例如生成一个服从标准正态分布的（均值为0，方差为1）的5个随机样本数组

array([ 0.83536852, -0.84927739, -2.56783843, -0.77170303,  1.55795624])

In [17]:
LIST2 = [[1,2],[3,4]] 
arr2 = np.array( [[1,2],[3,4]])#多维数组
print(arr2)

[[1 2]
 [3 4]]


numpy创建多维数组对象，ndarray是一种快速并且节省空间的多维数组，它可以提供数组化的算术运算和高级的广播功能。通过使用标准的数学函数，并不需要编写循环，便可以对整个数组的数据进行快速运算。除此之外ndarray还具备线性代数，随机数生成，和傅里叶变换的能力

In [18]:
print(LIST2[0][1])
print(arr2[0,1]) #返回第一行第二列的数值

2
2


In [19]:
np.zeros((2,3))#定义一个2行3列的0数组

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
np.random.normal(10,3,(2,4))#返回2行4列的array，且均值为10，标准差为3的正态分布的随机数

array([[ 13.63537572,  10.57113151,  14.37479229,   6.46644604],
       [  9.39902717,   8.49258547,  12.66839946,   6.95190764]])

In [21]:
arr1 = np.arange(8)

In [22]:
arr2 = np.arange(8).reshape(2,4)

In [23]:
print(arr1)

[0 1 2 3 4 5 6 7]


In [24]:
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]


In [25]:
arr1 = np.arange(8)
arr2 = arr1.reshape(2,4)#数组的元素总数不变，数组的形状可以随时改变
arr1[0] = 1000
print(arr1)
print(arr2)

[1000    1    2    3    4    5    6    7]
[[1000    1    2    3]
 [   4    5    6    7]]


In [26]:
arr3 = arr1.copy()
arr1[0]= 1
print(arr3)
print(arr1)
print(arr2)#引用类型，指向的是同一个内存地址，所以arr1改变后，arr3 和 arr2 也会一起改变。

[1000    1    2    3    4    5    6    7]
[1 1 2 3 4 5 6 7]
[[1 1 2 3]
 [4 5 6 7]]


In [27]:
print(arr2[1,2:3])
print(arr2[:,2])
print(arr2[1][2:4]) #返回第二行的第2，3列[2，4)

[6]
[2 6]
[6 7]


多维数组的属性

In [28]:
arr = arr2
print('Data type:',arr.dtype)
print('Total number of elements:',arr.size)
print("Number of dimensions:",arr.ndim)
print("Shape (dimensionality):",arr.shape)
print("Memory used (in bytes)",arr.nbytes)
print("Minimum and maximum:",arr.min(),arr.max())
print("Sum and product of all elements:",arr.sum(),arr.prod())
print("Mean and standard deviation:",arr.mean(),arr.std())
print("The sum of elements along the rows is:",arr.sum(axis = 1))#计算每一行的sum
print("The sum of elements along the columns is:",arr.sum(axis = 0))#计算每一列的sum

Data type: int32
Total number of elements: 8
Number of dimensions: 2
Shape (dimensionality): (2, 4)
Memory used (in bytes) 32
Minimum and maximum: 1 7
Sum and product of all elements: 29 5040
Mean and standard deviation: 3.625 2.11763429326
The sum of elements along the rows is: [ 7 22]
The sum of elements along the columns is: [ 5  6  8 10]


In [29]:
print("Array \n",arr)
print("Transpose \n",arr.T)#输出转置矩阵

Array 
 [[1 1 2 3]
 [4 5 6 7]]
Transpose 
 [[1 4]
 [1 5]
 [2 6]
 [3 7]]


# 数组的运算

Numpy专为科学计算而生，数组支持所有的常规运算，Numpy库中包含完整的基本科学函数，这些函数在数组的运算上也发挥了很大的作用，一般来说，数组的所有操作都是以元素对应的方式实现的，即同时应用于数组的所有元素，且一一对应。
Numpy提供的完整的数学函数，并且可以在整个数组上运行，其中包括对数、指数、三角函数和双曲三角函数等

In [30]:
x = np.linspace(0,2*np.pi,20)
y = np.sin(x) #在0，2pi之间的正弦函数上取20个点

In [31]:
print(y)

[  0.00000000e+00   3.24699469e-01   6.14212713e-01   8.37166478e-01
   9.69400266e-01   9.96584493e-01   9.15773327e-01   7.35723911e-01
   4.75947393e-01   1.64594590e-01  -1.64594590e-01  -4.75947393e-01
  -7.35723911e-01  -9.15773327e-01  -9.96584493e-01  -9.69400266e-01
  -8.37166478e-01  -6.14212713e-01  -3.24699469e-01  -2.44929360e-16]
